Reintrodce otel pin, pin to v1.19.0
Follow up to commit:
- https://github.com/cloudfoundry/guardian/commit/64f82b086a6daac6a72aec4b2d6bfa182006f1f1

We cannot fully remove the pin on otel, we still receive errors like:
```
go build  -gcflags=-trimpath=/root/go/src -buildmode=pie  -o bin/containerd -ldflags '-X github.com/containerd/containerd/version.Version=64f82b08 -X github.com/containerd/containerd/version.Revision=64f82b086a6daac6a72aec4b2d6bfa182006f1f1 -X github.com/containerd/containerd/version.Package=github.com/containerd/containerd -s -w ' -tags "no_btrfs urfave_cli_no_docs"  ./cmd/containerd
../../../go.opentelemetry.io/otel/sdk/trace/provider.go:90:30: cannot use &TracerProvider{} (value of type *TracerProvider) as "go.opentelemetry.io/otel/trace".TracerProvider value in variable declaration: *TracerProvider does not implement "go.opentelemetry.io/otel/trace".TracerProvider (missing method tracerProvider)
../../../go.opentelemetry.io/otel/sdk/trace/provider.go:170:10: cannot use t (variable of type *tracer) as "go.opentelemetry.io/otel/trace".Tracer value in return statement: *tracer does not implement "go.opentelemetry.io/otel/trace".Tracer (missing method tracer)
../../../go.opentelemetry.io/otel/sdk/trace/span.go:161:23: cannot use (*recordingSpan)(nil) (value of type *recordingSpan) as ReadWriteSpan value in variable declaration: *recordingSpan does not implement ReadWriteSpan (missing method span)
../../../go.opentelemetry.io/otel/sdk/trace/span.go:692:9: cannot use s.tracer.provider (variable of type *TracerProvider) as "go.opentelemetry.io/otel/trace".TracerProvider value in return statement: *TracerProvider does not implement "go.opentelemetry.io/otel/trace".TracerProvider (missing method tracerProvider)
../../../go.opentelemetry.io/otel/sdk/trace/span.go:780:20: cannot use nonRecordingSpan{} (value of type nonRecordingSpan) as "go.opentelemetry.io/otel/trace".Span value in variable declaration: nonRecordingSpan does not implement "go.opentelemetry.io/otel/trace".Span (missing method span)
../../../go.opentelemetry.io/otel/sdk/trace/span.go:811:74: cannot use s.tracer.provider (variable of type *TracerProvider) as "go.opentelemetry.io/otel/trace".TracerProvider value in return statement: *TracerProvider does not implement "go.opentelemetry.io/otel/trace".TracerProvider (missing method tracerProvider)
../../../go.opentelemetry.io/otel/sdk/trace/tracer.go:30:22: cannot use &tracer{} (value of type *tracer) as "go.opentelemetry.io/otel/trace".Tracer value in variable declaration: *tracer does not implement "go.opentelemetry.io/otel/trace".Tracer (missing method tracer)
../../../go.opentelemetry.io/otel/sdk/trace/tracer.go:47:21: impossible type assertion: p.(*recordingSpan)
	*recordingSpan does not implement "go.opentelemetry.io/otel/trace".Span (missing method span)
../../../go.opentelemetry.io/otel/sdk/trace/tracer.go:117:10: cannot use tr.newNonRecordingSpan(sc) (value of type nonRecordingSpan) as "go.opentelemetry.io/otel/trace".Span value in return statement: nonRecordingSpan does not implement "go.opentelemetry.io/otel/trace".Span (missing method span)
../../../go.opentelemetry.io/otel/sdk/trace/tracer.go:119:9: cannot use tr.newRecordingSpan(psc, sc, name, samplingResult, config) (value of type *recordingSpan) as "go.opentelemetry.io/otel/trace".Span value in return statement: *recordingSpan does not implement "go.opentelemetry.io/otel/trace".Span (missing method span)
../../../go.opentelemetry.io/otel/sdk/trace/tracer.go:119:9: too many errors
```

containerd did update the version of otel that it uses in this commit:
- https://github.com/containerd/containerd/commit/d106a7cdbe905ac201c15996a390542185088d6d
So we will update the otel pin from `1.15.1` to `1.19.0`.

Signed-off-by: Josh Russett <jrussett@vmware.com>